clcollins/srepd

pkg/tui/keymap.go
pkg/tui/tui.go

_feature_
Adds hotkeys to jump to top/bottom of list.
NA

Add top/bottom hotkeys

---

pkg/tui/commands.go
pkg/tui/tui.go

* Retrives alerts on startup
* Fixes loading message on startup
* Replaces broken "Retrieved X incidents" message with "Showing X/Y
incidents" to indicate team/user ownership
* Reworks table construction to simplify
* Adds more debug logging
Fixes #13

Retrieve alerts on startup

---

pkg/pd/pd.go
pkg/tui/commands.go
pkg/tui/tui.go

This will replace the client-side filtering of issues to remove issues
assigned to ignored users with an explicit list of userIDs to retrieve
issues for,  retrieved from the membership of the Teams specified in the config,
reducing the total volume of issues returned from PagerDuty.
Fixes #4 

Pass explicit list of users to GetIncidents

---

.gitignore
.goreleaser.yaml
Makefile

Adds goreleaser setup

---

Makefile

fixing goreleaser token

---

pkg/pd/pd.go

The team member retrieval was not properly handling paging results, and we were not getting the full list of user IDs for the team.  This PR fixes the paging issue, to return the full list.

Fix paging on team member retrieval

---

cmd/root.go
pkg/tui/commands.go

Deprecates usage/need for 'shell'

---

cmd/root.go
pkg/deprecation/deprecation.go

adds deprecation package; logs deprecated keys; sorts key

---

pkg/tui/views.go

adjusting string for "Assigned to" to make it more clear what you are looking at

---

pkg/tui/commands.go

Fixes a partially broken cluster login command mangled by a previous commit.

Fix a partially broken cluster login command

---

cmd/root.go
pkg/tui/commands.go
pkg/tui/model.go
pkg/tui/msgHandlers.go
pkg/tui/tui.go
pkg/tui/views.go

Improve content of data saved to the log file.
To try to track down some errors with actions being performed on previously selected incidents, this PR improves the logging by adding more structure, removing cruft and starts to add better log data.
1. Start to standardize format to more structured logging
Format: "$FUNCTION, ...key=value"
```text
eg: log.Debug("Update", msgType, msg) 
Produces: "DATE DEBUG Update messageType=messageContent"
eg: log.Debug("Update", msgType, msg, "someKey", "someValue")
Produces: "DATE DEBUG Update messageType=messageContent someKey=someValue"
```
2. remove redundant log messages
Update will print the message received, so no need to redeclare in the individual msg case matches
3. remove log messages before status update 
Status updates are logged already …

Improve log content

---

pkg/tui/views.go

Simplifies the incident view, compacting the output, adding some extra
data, and fixing some formatting.

Minor cleanup of incident view to simplify

---

Makefile

Update makefile to use goreleaser for build and install-local

---

pkg/pd/mock.go
pkg/pd/pd.go
pkg/tui/commands.go
pkg/tui/commands_test.go
pkg/tui/tui.go

Adds more unit tests

---

pkg/tui/tui.go

deselect selected incident if no longer in the issue list

---

README.md

adding some info badges

---

.github/actions/setup-go-from-mod/action.yml
.github/workflows/go-ci.yml

Adds a testing and linter validation workflow

Add testing and linter validation workflow

---

.github/actions/setup-go-from-mod/action.yml
.github/workflows/go-ci.yml
.goreleaser.yaml
Makefile

- **Add testing and linter validation workflow**
- **Fix missing .PHONY labels in Makefile**

ci workflow

---

README.md

fixing build status in readme.md

---

cmd/root.go
go.mod
go.sum
pkg/tui/commands.go
pkg/tui/commands_test.go
pkg/tui/msgHandlers.go
pkg/tui/tui.go

- **refactor silence msg handling and add tests**
- **Improve handling of incident wait msg**
- **Enable journal/system logging**

enable journal logging
